### PR TITLE
File Download, mailto:, whatsapp, sms

### PR DESCRIPTION
**Pull request by mining016**
Fixed working of file download, mailto , whatsapp , sms etc links by allowing it to handle directly.

### CODE REVIEW

**Comment by MindfulMe** [comment]
I see white screen alwats both local build and remote url

**Comment by MindfulMe** [comment]
Screenshot 2020-05-03 at 00 34 52
react app

**Comment by MindfulMe** [comment]
prefer this one https://github.com/react-native-community/react-native-webview

**Comment by mining016** [comment]
Hi,
Because you might have not uncomment 
 // mWebView.loadUrl("https://example.com");

above line.

**Comment by MindfulMe** [comment]
> Hi,
> Because you might have not uncomment
> // mWebView.loadUrl("https://example.com");
> 
> above line.

I did, tried everything. Platform MacOS, latest Android Studio

**Pull request closed without merging**
