### PR TITLE
Address the issue related to URL validation

### PR DESCRIPTION
**Pull request by luchua-bc**
Good afternoon Max,

Your repository webview is a very popular one with over three hundred forks, which is a nice project helping the open source community to develop with Android webview.

I noticed an issue that its URL validation has a flaw that doesn't validate the full domain. Would you please investigate and merge my pull request if you agree?

Thanks @slymax in advance for looking into this pull request.

@luchua-bc

### CODE REVIEW

**Comment by slymax** [comment]
Thanks for contributing, Bt2018! Do you have a specific example where the host isn't properly recognized?

**Comment by luchua-bc** [comment]
Hi Max,

Thanks for reviewing my request. I believe the intention is to validate hosts like www.example.com and web.example.com. However, an attacker can register a different domain e.g. myexample.com or anotherexample.com then invoking a URL of that fake domain will pass validation of the application and the URL will be loaded by the app as a trusted URL.

Regards,
@luchua-bc

**Comment by slymax** [comment]
That's a good point actually. I'd still leave the example without the leading dot though – otherwise urls without a hostname (including example.com) won't work. People can still add the dot if they need it.

**Comment by luchua-bc** [comment]
Thanks @slymax.

**Pull request merged**
